INSERT INTO public.dashboards (component_key, title, title_en, description, description_en, is_published, sort_order) VALUES
('dividend-yield','Dividend Yield on Cost e Crescita dei Dividendi','Dividend Yield on Cost & Growth','Yield on cost, crescita storica dei dividendi e proiezione del rendimento sul capitale investito.','Yield on cost, historical dividend growth and projected yield on invested capital.',true,10),
('sostenibilita-debito','Sostenibilità del Debito','Debt Service Coverage','Rapporto rate/reddito, soglia di sicurezza e impatto di una nuova rata.','Debt-to-income ratio, safety threshold and the impact of a new installment.',true,11),
('beta-volatilita','Beta e Volatilità del Portafoglio','Portfolio Beta & Volatility','Beta, alpha, correlazione e volatilità rispetto al benchmark.','Beta, alpha, correlation and volatility versus the benchmark.',true,12),
('rendimento-reale','Rendimento Reale e Inflazione','Real Return & Inflation','Capitale nominale e reale al netto dell''inflazione su orizzonti pluriennali.','Nominal versus inflation-adjusted capital over multi-year horizons.',true,13),
('twr-mwr','TWR vs MWR','TWR vs MWR','Differenza tra rendimento time-weighted e money-weighted (IRR) con flussi di cassa reali.','Time-weighted versus money-weighted (IRR) returns with real cash flows.',true,14),
('tracking-error','Tracking Error e Information Ratio','Tracking Error & Information Ratio','Scostamento di un fondo dal benchmark, tracking error annualizzato e information ratio.','Fund deviation from benchmark, annualized tracking error and information ratio.',true,15),
('costo-opportunita','Costo Opportunità degli Investimenti','Opportunity Cost Simulator','Confronto tra strategie alternative e liquidità ferma per quantificare il costo opportunità.','Compare alternative strategies and idle cash to quantify opportunity cost.',true,16),
('max-drawdown','Massimo Drawdown Storico','Maximum Drawdown History','Massimo drawdown, durata e recupero per diverse asset class.','Maximum drawdown, duration and recovery across asset classes.',true,17),
('asset-location','Asset Location e Efficienza Fiscale','Asset Location Efficiency','Distribuzione degli asset tra contenitori fiscali per ridurre il prelievo fiscale.','Allocating assets across tax wrappers to reduce the tax drag.',true,18),
('burn-rate-pensione','Burn Rate e Sostenibilità in Pensione','Retirement Burn Rate','Tassi di prelievo, rischio di esaurimento del capitale e strategie di decumulo.','Withdrawal rates, depletion risk and decumulation strategies.',true,19);